#!/usr/bin/env bash

set -e

OS="$(uname | awk '{print tolower($0)}')"
CONFIG="${OS}.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "base.conf.yaml" "${@}"

[[ "$OS" = "Darwin" ]] && plug="-p dotbot-brew/brew.py"
[[ "$OS" = "Linux" ]] && plug="-p dotbot_plugin_aptget/aptget.py"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" ${plug} -c "${CONFIG}" "${@}"